# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: email.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'email.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65mail.proto\x12\x04user\"K\n\x0bProductItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x02\x12\r\n\x05total\x18\x04 \x01(\x02\"\xd2\x02\n\x1dOrderConfirmationEmailRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x12\n\nevent_name\x18\x02 \x01(\t\x12\n\n\x02to\x18\x03 \x01(\t\x12#\n\x08products\x18\x04 \x03(\x0b\x32\x11.user.ProductItem\x12\x13\n\x0btotal_price\x18\x05 \x01(\x02\x12\x11\n\tfull_name\x18\x06 \x01(\t\x12\x10\n\x08order_id\x18\x07 \x01(\t\x12\x16\n\x0e\x63ustomer_phone\x18\x08 \x01(\t\x12\x18\n\x10\x64\x65livery_address\x18\t \x01(\t\x12\x12\n\npayment_id\x18\n \x01(\t\x12\x16\n\x0epayment_amount\x18\x0b \x01(\x02\x12\x16\n\x0epayment_method\x18\x0c \x01(\t\x12\x16\n\x0epayment_status\x18\r \x01(\t\x12\x12\n\norder_date\x18\x0e \x01(\t\"y\n%RegisterAndForgetPasswordEmailRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x12\n\nevent_name\x18\x03 \x01(\t\x12\x0b\n\x03otp\x18\x04 \x01(\t\x12\x11\n\tfull_name\x18\x05 \x01(\t\"1\n\rEmailResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9a\x02\n\x0c\x45mailService\x12U\n\x11RegisterSendEmail\x12+.user.RegisterAndForgetPasswordEmailRequest\x1a\x13.user.EmailResponse\x12[\n\x17\x46orgetPasswordSendEmail\x12+.user.RegisterAndForgetPasswordEmailRequest\x1a\x13.user.EmailResponse\x12V\n\x1aOrderConfirmationSendEmail\x12#.user.OrderConfirmationEmailRequest\x1a\x13.user.EmailResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'email_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTITEM']._serialized_start=21
  _globals['_PRODUCTITEM']._serialized_end=96
  _globals['_ORDERCONFIRMATIONEMAILREQUEST']._serialized_start=99
  _globals['_ORDERCONFIRMATIONEMAILREQUEST']._serialized_end=437
  _globals['_REGISTERANDFORGETPASSWORDEMAILREQUEST']._serialized_start=439
  _globals['_REGISTERANDFORGETPASSWORDEMAILREQUEST']._serialized_end=560
  _globals['_EMAILRESPONSE']._serialized_start=562
  _globals['_EMAILRESPONSE']._serialized_end=611
  _globals['_EMAILSERVICE']._serialized_start=614
  _globals['_EMAILSERVICE']._serialized_end=896
# @@protoc_insertion_point(module_scope)
