# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: email.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'email.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65mail.proto\x12\x04user\"`\n\x0c\x45mailRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x12\n\nevent_name\x18\x03 \x01(\t\x12\x0b\n\x03otp\x18\x04 \x01(\t\x12\x11\n\tfull_name\x18\x05 \x01(\t\"1\n\rEmailResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2D\n\x0c\x45mailService\x12\x34\n\tSendEmail\x12\x12.user.EmailRequest\x1a\x13.user.EmailResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'email_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMAILREQUEST']._serialized_start=21
  _globals['_EMAILREQUEST']._serialized_end=117
  _globals['_EMAILRESPONSE']._serialized_start=119
  _globals['_EMAILRESPONSE']._serialized_end=168
  _globals['_EMAILSERVICE']._serialized_start=170
  _globals['_EMAILSERVICE']._serialized_end=238
# @@protoc_insertion_point(module_scope)
