# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import email_pb2 as email__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in email_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmailServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterSendEmail = channel.unary_unary(
                '/user.EmailService/RegisterSendEmail',
                request_serializer=email__pb2.RegisterAndForgetPasswordEmailRequest.SerializeToString,
                response_deserializer=email__pb2.EmailResponse.FromString,
                _registered_method=True)
        self.ForgetPasswordSendEmail = channel.unary_unary(
                '/user.EmailService/ForgetPasswordSendEmail',
                request_serializer=email__pb2.RegisterAndForgetPasswordEmailRequest.SerializeToString,
                response_deserializer=email__pb2.EmailResponse.FromString,
                _registered_method=True)
        self.OrderConfirmationSendEmail = channel.unary_unary(
                '/user.EmailService/OrderConfirmationSendEmail',
                request_serializer=email__pb2.OrderConfirmationEmailRequest.SerializeToString,
                response_deserializer=email__pb2.EmailResponse.FromString,
                _registered_method=True)


class EmailServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterSendEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForgetPasswordSendEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrderConfirmationSendEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmailServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterSendEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSendEmail,
                    request_deserializer=email__pb2.RegisterAndForgetPasswordEmailRequest.FromString,
                    response_serializer=email__pb2.EmailResponse.SerializeToString,
            ),
            'ForgetPasswordSendEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.ForgetPasswordSendEmail,
                    request_deserializer=email__pb2.RegisterAndForgetPasswordEmailRequest.FromString,
                    response_serializer=email__pb2.EmailResponse.SerializeToString,
            ),
            'OrderConfirmationSendEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderConfirmationSendEmail,
                    request_deserializer=email__pb2.OrderConfirmationEmailRequest.FromString,
                    response_serializer=email__pb2.EmailResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.EmailService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user.EmailService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmailService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterSendEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.EmailService/RegisterSendEmail',
            email__pb2.RegisterAndForgetPasswordEmailRequest.SerializeToString,
            email__pb2.EmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForgetPasswordSendEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.EmailService/ForgetPasswordSendEmail',
            email__pb2.RegisterAndForgetPasswordEmailRequest.SerializeToString,
            email__pb2.EmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OrderConfirmationSendEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.EmailService/OrderConfirmationSendEmail',
            email__pb2.OrderConfirmationEmailRequest.SerializeToString,
            email__pb2.EmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
