name: Build and Deploy Event Service

on:
  push:
    branches:
      - dev
      - uat
      - prod
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout code for deployment
      uses: actions/checkout@v3

    - name: Create .env file
      run: echo "${{ vars.ENV }}" > .env

    - name: rsync deployments
      uses: burnett01/rsync-deployments@master
      with:
        switches: -avzr --delete
        path: ./
        remote_path: ${{vars.PATH}}/"${{ github.ref_name }}"
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_KEY }}

    - name: Start the Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ vars.PATH }}//"${{ github.ref_name }}"
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            sudo docker-compose up -d --build consumer-dev
          elif [[ "${{ github.ref }}" == "refs/heads/uat" ]]; then
            sudo docker-compose up -d --build consumer-uat
          elif [[ "${{ github.ref }}" == "refs/heads/uat" ]]; then
            sudo docker-compose up -d --build consumer-prod
          else
            echo "Unexpected branch"
            exit 1
          fi
          sudo docker image prune -a --force
