# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aws_lambda.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'aws_lambda.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ws_lambda.proto\x12\tinventory\"L\n\x07Product\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\t\x12\r\n\x05\x63olor\x18\x04 \x01(\t\"_\n\x11InventoryProducer\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x12\n\nevent_name\x18\x02 \x01(\t\x12$\n\x08products\x18\x03 \x03(\x0b\x32\x12.inventory.Product\"8\n\x14ProcessEventResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x61\n\x10InventoryService\x12M\n\x0cProcessEvent\x12\x1c.inventory.InventoryProducer\x1a\x1f.inventory.ProcessEventResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aws_lambda_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCT']._serialized_start=31
  _globals['_PRODUCT']._serialized_end=107
  _globals['_INVENTORYPRODUCER']._serialized_start=109
  _globals['_INVENTORYPRODUCER']._serialized_end=204
  _globals['_PROCESSEVENTRESPONSE']._serialized_start=206
  _globals['_PROCESSEVENTRESPONSE']._serialized_end=262
  _globals['_INVENTORYSERVICE']._serialized_start=264
  _globals['_INVENTORYSERVICE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
